import ProxmoxArch from "./ProxmoxArch";
import ProxmoxBios from "./ProxmoxBios";
import ProxmoxCloudInitType from "./ProxmoxCloudInitType";
import ProxmoxOsType from "./ProxmoxOsType";

interface ProxmoxVmOptions {
  vmid?: number;
  node?: string;
  acpi?: boolean;
  agent?: string;
  arch?: ProxmoxArch;
  archive?: string;
  args?: string;
  audio0?: string;
  autostart?: boolean;
  baloon?: number;
  bios?: ProxmoxBios;
  boot?: string;
  bootdisk?: string;
  bwlimit?: number;
  cdrom?: string;
  cicustom?: string;
  cipassword?: string;
  citype?: ProxmoxCloudInitType;
  ciuser?: string;
  cores?: number;
  cpu?: string;
  cpulimit?: number;
  cpuunits?: number;
  description?: string;
  efidisk0?: string;
  force?: boolean;
  freeze?: boolean;
  hookscript?: string;
  hotplug?: string;
  hugepages?: "any" | 2 | 1024;
  ide0?: string;
  ide1?: string;
  ide2?: string;
  ide3?: string;
  kvm?: boolean;
  lock?: boolean;
  machine?: string;
  memory?: number;
  name?: string;
  numa?: boolean;
  ostype?: ProxmoxOsType;
  pool?: string;
  protection?: boolean;
  reboot?: boolean;
  sata0?: string;
  sata1?: string;
  sata2?: string;
  sata3?: string;
  sata4?: string;
  sata5?: string;
  scsi0?: string;
  scsi1?: string;
  scsi2?: string;
  scsi3?: string;
  scsi4?: string;
  scsi5?: string;
  scsi6?: string;
  scsi7?: string;
  sockets?: number;
  start?: boolean;
  storage?: string;
  tags?: string;
  template?: boolean;
  unique?: boolean;
  net0?: string;
  net1?: string;
    net2?: string;
    onboot?: boolean;
}

export default ProxmoxVmOptions;
